ram:
  service: http://192.168.0.2:3000
  cas_server: https://192.168.0.2
development:
  service: http://192.168.0.2:3000
  cas_server: https://192.168.0.2
production:
  service: http://accounts.jurnalo.com
  cas_server: https://login.jurnalo.com
justus:
  service: http://localhost:3000
  cas_server: https://login.jurnalo.com