ram:
  service: http://localhost:3000
  cas_server: https://localhost
development:
  service: http://localhost:3000
  cas_server: https://localhost
production:
  service: http://accounts.jurnalo.com
  cas_server: https://login.jurnalo.com
justus:
  service: http://localhost:3000
  cas_server: https://login.jurnalo.com
