ram:
  path: /Users/ram/Workspace/jurnalo/JModels
development:
  path: /Users/ram/Workspace/jurnalo/JModels 
production:
  path: /home/jurnalo/apps/JModels/current
justus:
  path: /Users/justus/JModels
cached:
  path: /Users/ram/Workspace/jurnalo/JModels